services:
  - type: web
    name: smartbroadband-app
    env: node
    plan: free
    buildCommand: "npm install && npm run render-build"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: smartbroadband-db
          property: connectionString

databases:
  - name: smartbroadband-db
    plan: free


